// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

/*
Package bigtabledriver is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	Vector
*/
package bigtabledriver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vector struct {
	DataType string   `protobuf:"bytes,1,opt,name=DataType" json:"DataType,omitempty"`
	Data     [][]byte `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (m *Vector) Reset()                    { *m = Vector{} }
func (m *Vector) String() string            { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()               {}
func (*Vector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vector) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Vector) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Vector)(nil), "bigtabledriver.Vector")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4b, 0xca, 0x4c, 0x2f, 0x49, 0x4c, 0xca, 0x49,
	0x4d, 0x29, 0xca, 0x2c, 0x4b, 0x2d, 0x52, 0xb2, 0xe0, 0x62, 0x0b, 0x4b, 0x4d, 0x2e, 0xc9, 0x2f,
	0x12, 0x92, 0xe2, 0xe2, 0x70, 0x49, 0x2c, 0x49, 0x0c, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x85, 0x84, 0xb8, 0x58, 0x40, 0x6c, 0x09, 0x26, 0x05, 0x66, 0x0d,
	0x9e, 0x20, 0x30, 0x3b, 0x89, 0x0d, 0x6c, 0xa0, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xee, 0xa8,
	0xd4, 0xb0, 0x5e, 0x00, 0x00, 0x00,
}
