// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

/*
Package boltdriver is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	Vector
*/
package boltdriver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vector struct {
	Clock    int64    `protobuf:"varint,1,opt,name=clock" json:"clock,omitempty"`
	Count    int64    `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	DataType string   `protobuf:"bytes,3,opt,name=DataType" json:"DataType,omitempty"`
	Data     [][]byte `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (m *Vector) Reset()                    { *m = Vector{} }
func (m *Vector) String() string            { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()               {}
func (*Vector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vector) GetClock() int64 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *Vector) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Vector) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Vector) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Vector)(nil), "boltdriver.Vector")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xca, 0xcf, 0x29, 0x49, 0x29, 0xca, 0x2c,
	0x4b, 0x2d, 0x52, 0x4a, 0xe1, 0x62, 0x0b, 0x4b, 0x4d, 0x2e, 0xc9, 0x2f, 0x12, 0x12, 0xe1, 0x62,
	0x4d, 0xce, 0xc9, 0x4f, 0xce, 0x96, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0x70, 0xc0, 0xa2,
	0xf9, 0xa5, 0x79, 0x25, 0x12, 0x4c, 0x50, 0x51, 0x10, 0x47, 0x48, 0x8a, 0x8b, 0xc3, 0x25, 0xb1,
	0x24, 0x31, 0xa4, 0xb2, 0x20, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0x33, 0x08, 0xce, 0x17, 0x12,
	0xe2, 0x62, 0x01, 0xb1, 0x25, 0x58, 0x14, 0x98, 0x35, 0x78, 0x82, 0xc0, 0xec, 0x24, 0x36, 0xb0,
	0xc5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x35, 0x58, 0x25, 0x97, 0x86, 0x00, 0x00, 0x00,
}
